### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by spinda** [GervinFung/ts-add-js-extension#56] opened 2023-07-15 00:26 UTC
```
$ npx ts-add-js-extension --help
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /home/spinda/.npm/_npx/9481ecb1b35cd9d7/node_modules/ts-add-js-extension/build/cjs/read-write.js
- /home/spinda/.npm/_npx/9481ecb1b35cd9d7/node_modules/ts-add-js-extension/build/cjs/index.js
- /home/spinda/.npm/_npx/9481ecb1b35cd9d7/node_modules/ts-add-js-extension/build/cjs/bin.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/spinda/.npm/_npx/9481ecb1b35cd9d7/node_modules/ts-add-js-extension/build/cjs/read-write.js:44:36)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/spinda/.npm/_npx/9481ecb1b35cd9d7/node_modules/ts-add-js-extension/build/cjs/read-write.js',
    '/home/spinda/.npm/_npx/9481ecb1b35cd9d7/node_modules/ts-add-js-extension/build/cjs/index.js',
    '/home/spinda/.npm/_npx/9481ecb1b35cd9d7/node_modules/ts-add-js-extension/build/cjs/bin.js'
  ]
}

Node.js v18.12.1
```

**Comment by GervinFung** [comment] 2023-07-15 05:31
Oh crap @spinda, thanks for pointing it out, I forgot to move `typescript` into `dependencies`, thanks for pointing it out! Really appreciate it

**Comment by GervinFung** [comment] 2023-07-15 05:46
@spinda, I published the package again with the fix for this problem, u can try again

**Comment by GervinFung** [comment] 2023-07-21 07:43
@spinda, have u tried the latest version?

**Comment by Artawower** [comment] 2023-07-24 22:08
Hello, I don't know if this is related to this problem, but I got the following error when trying to use it: 
```
node:internal/modules/cjs/loader:1074
    throw new ERR_REQUIRE_ESM(filename, true);
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/darkawower/.npm-global/lib/node_modules/ts-add-js-extension/build/cjs/a.mjs not supported.
Instead change the require of /Users/darkawower/.npm-global/lib/node_modules/ts-add-js-extension/build/cjs/a.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/darkawower/.npm-global/lib/node_modules/ts-add-js-extension/build/cjs/bin.js:8:15) {
  code: 'ERR_REQUIRE_ESM'
  ```
I'm trying to use the package from the CLI

**Comment by GervinFung** [comment] 2023-07-25 07:10
> 

@Artawower Oh my God, I accidentally committed temp file and published it. I published the latest version, it fixed your problem

**Comment by Artawower** [comment] 2023-07-25 09:25
Thanks for the quick fix, everything works without error messages. Can you please advise me how I can find out why my imports in the files did not change after the script finished?

I am trying to add extensions to a file for the typescript module-generated code

**Comment by GervinFung** [comment] 2023-07-31 05:56
@Artawower any updates on ur issue?

**Comment by Artawower** [comment] 2023-07-31 20:20
Sorry for the delayed reply.
Branch for test: https://github.com/Artawower/second-brain-publisher/tree/test/codegen
Command: `convert:api2`

Expected behavior:
All imports inside src/generated directory have relative paths and *.js extension

Real behavior:
Nothing has changed

**Comment by GervinFung** [comment] 2023-08-03 02:47
@Artawower

I want to clarify that the matter I'm raising is not an issue per se; rather, it's about aligning the purpose of ts-add-js-extension. I am not fully aware of how other tools operate, but in ur particular case, u already have a similar tool called `fix-esm-import-path`. That tool is capable of modifying the import/export paths of TypeScript (src) code

As a matter of principle, I adhere to the practice of modifying the transpiled code exclusively. Therefore, I focus on adding the JavaScript file extension to the import/export paths in the `dist` files rather than the `src` files. This decision stems from the fact that I primarily import/export TypeScript files within the src directory, not JavaScript files, hence I do not modify the import/export path to include build artifacts, when none of it exist

Consequently, for my import/export statements within src, I have two options:

1. Omitting the file extension
2. Appending the TypeScript file extension

**Comment by GervinFung** [comment] 2023-08-20 11:07
@Artawower  how are things going? Did I answer your question?

**Comment by Artawower** [comment] 2023-08-20 16:51
Yes, thanks for the reply, everything is fine! As you noticed above, I am using a different tool and in this post I just wanted to highlight the problem I saw.

I get your point, if your tool was intended that way that's ok

Personally I don't see much difference between dist directory and src directory, ultimately the only difference is the path... In that case it's just a matter of tool flexibility.

**Closed** 2023-08-21 01:12 UTC
